apiVersion: v1
# Service sets up networking in a Kubernetes Cluster.
# Service has 4 subtypes:
#
# ClusterIP
# NodePort -> Exposes a container to outside world
# LoadBalancer
# Ingress
kind: Service
metadata:
  name: client-node-port
spec:
  type: NodePort
  ports:
      # port property is going to be the port that another
      # container inside our application could access.
    - port: 3050
      # targetPort is the port inside the pod that we want to
      # open up traffic to.
      targetPort: 3000
      # nodePort allows users to access the Pod via the browser.
      # It needs to be between 30000-32767
      nodePort: 31515
  # selector refers to metadata/labes/component and links those
  # objects together
  selector:
    component: web